
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RubyBlog_development
  username: oleksii
  password: 1111
  host: localhost
  port: 5432

test:
  <<: *default
  database: RubyBlog_test

production:
  <<: *default
  database: RubyBlog_production
  username: RubyBlog
  password: <%= ENV['RUBYBLOG_DATABASE_PASSWORD'] %>
